"use strict";
// IDs stay stable for saved selections and older online clients. Portrait indexes refer to roster-atlas.png.
const characters=[
  {id:"gear",name:"메카",gender:"남",portrait:0,icon:"🤖",color:"#4caeff",role:"2단계 로봇 파일럿",description:"로봇이 파괴되면 파일럿이 같은 목숨으로 탈출합니다.",traits:["중장갑","로봇 HP","폭발 탈출","고속 파일럿","넉백 저항","재가동"],hp:155,pilotHp:55,speed:170,attack:{name:"중화기 미사일",damage:23,speed:610,range:590,size:11,splash:32,cooldown:.34},pilotAttack:{name:"파일럿 블래스터",damage:14,speed:850,range:570,size:5,cooldown:.19},skill:{name:"과부하 장갑",type:"mechGuard",cooldown:11},super:{name:"메카 재가동",type:"reboot"}},
  {id:"flame",name:"화린",gender:"남",portrait:1,icon:"🔥",color:"#ff6550",role:"화염술사",description:"화상 상태의 적을 다시 태워 폭발시킵니다.",traits:["화상 탄환","지속 불길","화상 연계","화염 고리","유성 폭발","수풀 점화"],hp:94,speed:225,attack:{name:"불씨탄",damage:16,speed:690,range:560,size:8,status:"burn"},skill:{name:"화염 고리",type:"flameRing",cooldown:10},super:{name:"유성 화염",type:"meteor"}},
  {id:"jumper",name:"점핑 잭",gender:"남",portrait:2,icon:"🦘",color:"#55d69a",role:"점프 전사",description:"장애물을 넘어 지정 착지점에 충격파를 일으킵니다.",traits:["빠른 이동","단거리 도약","공중 회피","지정 착지점","착지 충격파","연속 점프"],hp:105,speed:245,attack:{name:"체공 탄환",damage:18,speed:720,range:575,size:7},skill:{name:"연속 도약",type:"vault",cooldown:9},super:{name:"슈퍼점프",type:"jump"}},
  {id:"frost",name:"쉘",gender:"여",portrait:3,icon:"❄️",color:"#7bcaff",role:"빙결 마법사",description:"냉기 3중첩으로 적을 묶고 빙결 지대를 만듭니다.",traits:["냉기 중첩","3중첩 빙결","얼음 지대","광역 눈보라","빙판 보정","이동 억제"],hp:96,speed:215,attack:{name:"얼음 화살",damage:16,speed:700,range:580,size:8,status:"chill"},skill:{name:"빙결 지대",type:"icePatch",cooldown:10},super:{name:"절대빙결",type:"blizzard"}},
  {id:"volt",name:"우르",gender:"남",portrait:4,icon:"⚡",color:"#ffd45c",role:"연쇄 번개 사냥꾼",description:"공격으로 충전하고 가까운 적에게 전기를 전파합니다.",traits:["전기 탄환","충전 게이지","충전 탄 강화","연쇄 감전","순간 가속","낙뢰 포화"],hp:90,speed:240,attack:{name:"전기 구체",damage:15,speed:805,range:615,size:7,status:"shock"},skill:{name:"연쇄 번개",type:"chain",cooldown:9},super:{name:"낙뢰 폭발",type:"storm"}},
  {id:"healer",name:"모리스",gender:"여",portrait:7,icon:"💧",color:"#59c6f6",role:"물 조작사",description:"물탄으로 적을 적시고 웅덩이에서 속도를 얻습니다.",traits:["물탄","젖음 상태","물 연계 피해","물 웅덩이","웅덩이 회복","물길 가속"],hp:102,speed:220,attack:{name:"물살 공격",damage:16,speed:700,range:560,size:8,status:"wet"},skill:{name:"치유 물결",type:"waterPool",cooldown:11},super:{name:"거대 파도",type:"tidal"}},
  {id:"sniper",name:"모스코",gender:"남",portrait:6,icon:"🌬️",color:"#5de7cc",role:"바람 사수",description:"긴 사거리의 바람 칼날로 적의 위치를 무너뜨립니다.",traits:["원거리 칼날","기본 넉백","회오리 견제","자기 가속","밀어내기","길목 장악"],hp:92,speed:225,attack:{name:"바람 화살",damage:19,speed:900,range:750,size:6,knockback:28,cooldown:.37},skill:{name:"회오리",type:"gust",cooldown:10},super:{name:"폭풍 칼날",type:"tornado"}},
  {id:"trick",name:"오리엔",gender:"남",portrait:8,icon:"🪽",color:"#b085f2",role:"공중 암살자",description:"짧은 비행으로 벽을 넘고 급강하 공격을 합니다.",traits:["깃털 탄환","짧은 비행","벽 넘기","공중 회피","급강하 폭발","정찰 시야"],hp:92,speed:235,attack:{name:"깃털 칼날",damage:17,speed:750,range:590,size:7},skill:{name:"짧은 비행",type:"flight",cooldown:10},super:{name:"급강하",type:"dive"}},
  {id:"earth",name:"바위르",gender:"남",portrait:5,icon:"🪨",color:"#c5925f",role:"지진 전사",description:"지진 중심부에 큰 피해를 주고 균열을 다시 무너뜨립니다.",traits:["중심 피해","외곽 감속","바닥 균열","2차 붕괴","낙석","높은 체력"],hp:140,speed:185,attack:{name:"바위 탄",damage:21,speed:595,range:530,size:11},skill:{name:"지진 내리치기",type:"quake",cooldown:11},super:{name:"대지 붕괴",type:"collapse"}},
  {id:"wind",name:"섬광",gender:"남",portrait:9,icon:"✨",color:"#ffe081",role:"빛의 기동 전사",description:"눈부신 돌진과 잔상으로 상대 조준을 흔듭니다.",traits:["초고속 이동","섬광 탄환","잔상 회피","순간 돌진","조준 방해","빛의 폭발"],hp:88,speed:265,attack:{name:"빛 파편",damage:16,speed:835,range:590,size:6},skill:{name:"섬광 돌진",type:"flashDash",cooldown:9},super:{name:"빛의 폭발",type:"flashBurst"}},
  {id:"shadow",name:"베놈",gender:"남",portrait:10,icon:"☠️",color:"#b764e4",role:"독술사",description:"독을 쌓아 전염시키고 웅덩이를 폭발시킵니다.",traits:["독 중첩","지속 피해","독 웅덩이","중독 전염","독 폭발","적 약화"],hp:95,speed:230,attack:{name:"독 투척",damage:14,speed:680,range:550,size:9,status:"poison"},skill:{name:"독 구름",type:"poisonPool",cooldown:11},super:{name:"맹독 폭발",type:"venomBurst"}},
  {id:"alchemist",name:"플랜트",gender:"여",portrait:11,icon:"🌿",color:"#91da73",role:"식물 소환사",description:"씨앗을 심고 자란 덩굴로 자신만의 영역을 만듭니다.",traits:["씨앗 탄환","씨앗 성장","덩굴 속박","소환 식물","가시 지대","지역 장악"],hp:102,speed:215,attack:{name:"씨앗 탄환",damage:15,speed:675,range:555,size:8,status:"seed"},skill:{name:"덩굴 소환",type:"seedling",cooldown:11},super:{name:"생명의 숲",type:"forest"}},
  {id:"music",name:"타임슬리퍼",gender:"남",portrait:12,icon:"⏳",color:"#efae63",role:"시간 조작사",description:"위치 기록을 이용해 되감고 적만 느리게 합니다.",traits:["시간 표식","적 감속","자기 가속","위치 기록","피해 복구","되감기"],hp:95,speed:225,attack:{name:"시간 파편",damage:17,speed:735,range:570,size:8,status:"time"},skill:{name:"시간 가속",type:"timeShift",cooldown:11},super:{name:"시간 되감기",type:"rewind"}},
  {id:"plant",name:"켄조",gender:"여",portrait:13,icon:"🎵",color:"#f871bd",role:"소리술사",description:"박자에 맞는 공격으로 음파를 키우고 적을 밀어냅니다.",traits:["음파 탄환","박자 보너스","진동 중첩","충격 넉백","소리 장벽","광역 폭발"],hp:104,speed:220,attack:{name:"음파 탄환",damage:17,speed:710,range:580,size:8,status:"vibration"},skill:{name:"진동 파동",type:"echo",cooldown:10},super:{name:"음파 폭발",type:"sonic"}},
  {id:"star",name:"리코트",gender:"남",portrait:14,icon:"👻",color:"#94c7ff",role:"생명 조작사",description:"한 목숨에 한 번 치명타를 버티고 영혼으로 되돌아옵니다.",traits:["영혼 탄환","소량 흡혈","영혼 보호","치명타 유예","제한 부활","영혼 포화"],hp:93,speed:225,attack:{name:"영혼 탄환",damage:17,speed:745,range:590,size:8,status:"soul"},skill:{name:"영혼 보호",type:"soulGuard",cooldown:12},super:{name:"혼령 행렬",type:"spirits"}}
];
if(typeof module!=="undefined"&&module.exports)module.exports=characters;
if(typeof window!=="undefined")window.YungeonCharacters=characters;
