(() => {
  "use strict";
  const W=720,H=1080,TAU=Math.PI*2,canvas=document.getElementById("game"),ctx=canvas.getContext("2d");
  const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);
  const d2=(a,b,c,d)=>(a-c)**2+(b-d)**2;
  const roster=window.YungeonCharacters,combat=window.YungeonCombat,sound=window.YungeonSound;
  const walls=[[273,217,174,30],[273,815,174,30],[207,318,30,103],[483,318,30,103],[207,659,30,105],[483,659,30,105],[207,390,96,30],[417,390,96,30],[207,660,96,30],[417,660,96,30],[0,452,98,45],[622,452,98,45],[0,585,98,45],[622,585,98,45],[69,382,30,116],[621,382,30,116],[69,584,30,116],[621,584,30,116],[0,296,98,30],[622,296,98,30],[0,754,98,30],[622,754,98,30],[0,0,60,48],[660,0,60,48],[0,1032,60,48],[660,1032,60,48]];
  const waters=[[0,0,93,278],[627,0,93,278],[0,497,93,88],[627,497,93,88],[0,800,93,280],[627,800,93,280]];
  const bushes=[[273,152,174,66],[238,333,245,62],[238,686,245,78],[273,845,174,79]];
  const words=[["ek’elenol","에길레노","기분 좋을 때 쓰는 단어"],["emileno","에밀레노","엄마"],["ebileno","에빌레노","아빠"],["insane","인세네","극도한"],["espanol de mara","이스파놀 더 마라","스페인어 해봐"],["Dance bari","댄스바리","댄스파티"],["Golin Bit Thongg","구런 빛 똥","사랑해"],["Golioli Galigali Goligali Ga","구리구리 가리가리 구리가리 까","그냥 노래 부르는 것"],["agolalo","에고라로","기분이 Dirty 할 때 쓰는 단어"],["ogolalo","오고라로","에길레노의 사투리"],["babaooIlala","바바울랄라","거시기 (기억이 잘 안나는 것을 지칭할 때의 거시기)"],["Let’s go baby","레츠 고 베이비","빨리 가자 녀석들아"],["mokgolelo","먹고레로","미식부"],["ae","예","1"],["el","엘","2"],["me’","메","3"],["zo","조","4"],["pa","파","5"],["de’","데","6"],["luc","럭","7"],["Hosbi","호스비","8"],["Gouten","구텐","9"],["burg","베르크","0"],["ajuol leno","아절레노","아저씨"],["ajoo leno","아주레노","아줌마"],["le","레","나"],["no","노","너"],["egil","에길","남자"],["megil","메길","여자"],["fellow","펠로","그들"],["BBallo","빨로","그 녀석들"],["egilmegileno","에길메길레노","성별"],["ebiuleno","이별레노","탈퇴, 헤어짐"],["gouleno","고울레노","절교"],["oola","울라","아"],["excu’ne","엑스쿠네","변명"],["nomaleno","노멀레노","안멀다고, 안멀다고"],["maleno","멀레노","멀다고, 안멀다고"],["wakard","와카드","구닥다리"],["co’lone","콜로네","춥다"],["ha’lole","할로네","덥다"],["haluleno","할루레노","안녕하세요, 안녕"],["TThenkcoleno","땡콜레노","감사합니다"],["nogoleno","노골레노","싫다, 싫어하다"],["goleno","골레노","좋다, 좋아하다"],["frendeno","프렌데노","친구"],["mo’ne","머네","돈"],["cocoleno","코콜레노","시간"],["ne’","네","~은, ~는, 이, 가"],["de’ne","데네","오늘"],["do’ne","도네","내일"],["dele’ne","델레네","모레"],["di’ne","디네","어제"],["dedoni’ne","데도니네","이번주"],["deldode","델도데","다음주"],["dedoni’ne deldone","데도니네 델도네","다다음주"],["mido’ne","미도네","만나다"],["sumongleno","수멍레노","멍청이, 바보"],["nomoleno","노모레노","망할"],["nogrisa haleu","구러싸 할르","싸가지가 없는 (할르 대신 ‘르’를 쓰면 싸가지가 있다로 대체가능)"],["bokerano","보께라노","양아치, 비행청소년"],["basahi","바사이","쓰레기"],["haleu","할르","없다"],["leu","르","있다"],["aguda haleu","아구다 할르","눈치가 없는(할르 대신 ‘르’를 쓰면 눈치가 있다로 대체가능)"],["haleu pole’","할르 폴레","못한다(할르 대신 ‘르’를 쓰면 할수 있다로 대체가능)"],["amide","올라 아미대","人馬 (한자니 그대로 발음하세요)"],["maloi","말로이","나쁜"],["loi","로이","착한"],["piroki","피로키","불량한, 불량"],["susno","서쓰노","화학물질을 나타내는 말에 붙는 말"],["naturoomsusno","나트룸써쓰노","나트륨"],["goyonsansusno","구연산써쓰노","구연산"],["sone","소네","음식을 나타내는 말에 붙는 말"]];
  const spawn=[[360,965],[360,96],[150,535],[570,535]];
  const rewardNames={shield:"🛡 2회 피격 방어막",heal:"💚 체력 +45",boost:"⚡ 공격 강화 10초",super:"✦ 필살기 +60%"};
  const escMap={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"};
  const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>escMap[c]);
  let selectedCharacterId=localStorage.getItem("yungeonCharacter")||"gear";
  if(!roster.some(c=>c.id===selectedCharacterId))selectedCharacterId="gear";
  let mode="menu",onlineStatus="",roomCode="",myId=0,hostId=0,ws=null;
  let players=[],bullets=[],fields=[],effects=[],timeLeft=180,clock=0,frame=0,last=performance.now();
  let fireHeld=false,angle=-Math.PI/2,moveTouch={x:0,y:0},keys=new Set(),challenge=null,nextChallenge=0,lastAutoChallenge=0;
  let toastTimer=0,endShown=false,jumpTargeting=false,pointerPosition=null;
  let authToken="",accountProfile=null,lastEarned=null;
  const show=(id,visible)=>$(id).classList.toggle("hidden",!visible);
  const nowGame=()=>mode==="online"?Date.now():performance.now();
  const me=()=>players.find(p=>p.id===myId);
  function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2300);}
  function blocked(x,y,r=19){if(!Number.isFinite(x)||!Number.isFinite(y)||x<r||y<r||x>W-r||y>H-r)return true;return [...walls,...waters].some(([a,b,w,h])=>x+r>a&&x-r<a+w&&y+r>b&&y-r<b+h);}
  function moveTo(p,x,y){if(!blocked(x,y)){p.x=x;p.y=y;return true;}return false;}
  function move(p,dx,dy,dt){const now=nowGame();if(p.rootUntil>now||p.jump)return;const len=Math.hypot(dx,dy);if(len<.01)return;let speed=combat.getCharacter(p.characterId).speed;if(p.slowUntil>now)speed*=.57;if(p.speedBuffUntil>now)speed*=1.3;const vx=dx/len*speed*dt,vy=dy/len*speed*dt;moveTo(p,p.x+vx,p.y);moveTo(p,p.x,p.y+vy);}
  function newPlayer(id,name,x,y,characterId,bot=false){const c=combat.getCharacter(characterId),now=performance.now();return{id,name,x,y,characterId:c.id,color:c.color,bot,hp:c.hp,maxHp:c.hp,ammo:3,super:0,ko:0,deaths:0,angle:-Math.PI/2,shieldHits:0,alive:true,respawnAt:0,invulnUntil:now+3000,skillReadyAt:0,lastShot:-1000,lastReload:now,lastHurt:now,bonusDamageUntil:0,fastFireUntil:0,speedBuffUntil:0,stealthUntil:0,burnUntil:0,poisonUntil:0,slowUntil:0,rootUntil:0,jump:null,aiDir:0,aiChange:0};}
  function particle(x,y,color,n=8,scale=1){for(let i=0;i<n;i++)effects.push({x,y,vx:rand(-110,110)*scale,vy:rand(-150,55)*scale,life:rand(.25,.6),max:.6,size:rand(3,7)*scale,color});}
  function floating(x,y,label,color="#fff"){effects.push({x,y,vx:rand(-15,15),vy:-75,life:.9,max:.9,text:label,color});}
  function visualEvent(ev,local=false){if(!ev)return;
    if(ev.type==="shot"){particle(ev.x,ev.y,ev.color||"#ffe6a3",5,.6);if(local||mode==="online")sound.play("shoot");}
    if(ev.type==="hit"||ev.type==="shieldHit"){particle(ev.x,ev.y,ev.type==="hit"?"#ffe2a2":"#9deeff",12);floating(ev.x,ev.y-28,ev.type==="hit"?`-${Math.ceil(ev.damage)}`:"실드!",ev.type==="hit"?"#fff0b1":"#acf2ff");sound.play("hit");}
    if(ev.type==="ko"){particle(ev.x,ev.y,"#ffca73",28,1.6);toast(`${ev.name} ⚡ ${ev.target} KO!`);sound.play("ko");}
    if(ev.type==="reward"){particle(ev.x,ev.y,"#e4abff",24,1.4);sound.play("item");}
    if(ev.type==="respawn"){particle(ev.x,ev.y,"#9af5ff",22);sound.play("respawn");}
    if(ev.type==="skill"){particle(ev.x,ev.y,ev.color||"#aaf9df",14);sound.play("skill");}
    if(ev.type==="super"){particle(ev.x,ev.y,ev.color||"#ebadff",22,1.2);sound.play("super");}
    if(ev.type==="jump"){particle(ev.x,ev.y,ev.color||"#ffd36e",18);sound.play("jump");}
    if(ev.type==="land"){particle(ev.x,ev.y,ev.color||"#ffd36e",34,1.8);sound.play("land");}
    if(ev.type==="blast"||ev.type==="field"||ev.type==="dash"||ev.type==="heal")particle(ev.x,ev.y,ev.color||"#c7f5df",18,1.1);
    if(ev.type==="beam")for(let i=0;i<18;i++)particle(ev.x+(ev.toX-ev.x)*i/18,ev.y+(ev.toY-ev.y)*i/18,ev.color||"#fff",1,.5);
  }
  function soloDamage(target,amount,ownerId){const now=performance.now();if(!target.alive||target.jump||target.invulnUntil>now)return false;if(target.shieldHits>0){target.shieldHits--;visualEvent({type:"shieldHit",x:target.x,y:target.y,id:target.id},true);return false;}
    target.hp=Math.max(0,target.hp-amount);target.lastHurt=now;const owner=players.find(p=>p.id===ownerId);if(owner&&owner.id!==target.id)owner.super=clamp(owner.super+14,0,100);visualEvent({type:"hit",x:target.x,y:target.y,id:target.id,damage:amount},true);
    if(target.hp<=0){target.alive=false;target.deaths++;target.respawnAt=now+5000;target.jump=null;if(owner&&owner.id!==target.id)owner.ko++;visualEvent({type:"ko",x:target.x,y:target.y,name:owner?.name||"전장",target:target.name},true);}return true;
  }
  const soloWorld={fields,now:()=>performance.now(),players:()=>players,hit:soloDamage,canStand:(x,y,r)=>!blocked(x,y,r),moveTo,
    push:(p,dx,dy)=>{for(let i=0;i<6;i++){moveTo(p,p.x+dx/6,p.y);moveTo(p,p.x,p.y+dy/6);}},
    shot:(p,a,options)=>{const speed=options.speed||700,range=options.range||560;bullets.push({x:p.x+Math.cos(a)*27,y:p.y+Math.sin(a)*27,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:range/speed,owner:p.id,damage:options.damage||18,size:options.size||8,status:options.status||null,color:options.color||p.color,superShot:(options.damage||0)>=35});},
    effect:ev=>visualEvent(ev,true)};
  function renderCharacterSelect(){const c=combat.getCharacter(selectedCharacterId);$("selectedCharacterName").textContent=c.name;$("pilotName").textContent=me()?.name||c.name;document.querySelector(".pilot-face").textContent=c.icon;
    $("characterGrid").innerHTML=roster.map(v=>`<button class="character-card ${v.id===c.id?"selected":""}" data-character="${v.id}" style="--fighter:${v.color}"><span class="icon">${v.icon}</span><b>${escapeHtml(v.name)}</b><small>${escapeHtml(v.role)}</small></button>`).join("");
    $("characterDetail").innerHTML=`<b>${c.icon} ${escapeHtml(c.name)} · ${escapeHtml(c.role)}</b><br>${escapeHtml(c.description)}<br>체력 ${c.hp} · 속도 ${c.speed} · 원거리 공격 ${escapeHtml(c.attack.name)} (${c.attack.damage})<br>일반 스킬 ${escapeHtml(c.skill.name)} (${c.skill.cooldown}초) · 필살기 ${escapeHtml(c.super.name)}`;
    $("characterGrid").querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedCharacterId=b.dataset.character;localStorage.setItem("yungeonCharacter",selectedCharacterId);renderCharacterSelect();});
  }
  function renderAccount(){const p=accountProfile;show("accountFormPanel",!p);show("accountProfilePanel",!!p);$("accountOpenBtn").textContent=p?`👤 ${p.name} · ${p.tier} ${p.points}점`:"👤 Google 로그인";$("sideAccountBtn").textContent=p?"계정 보기":"Google 로그인";
    if(!p){$("sideAccount").innerHTML='<div class="account-small">Google로 로그인하면 온라인 대전 기록이 저장됩니다.</div>';return;}
    $("sideAccount").innerHTML=`<span class="account-tier">${escapeHtml(p.tier)}</span><div class="account-points">${p.points} P</div><div class="account-small">${escapeHtml(p.name)} · ${p.matches}전 ${p.wins}승 · 누적 ${p.totalKo} KO</div>`;
    $("accountNameDisplay").textContent=p.name;$("accountTierDisplay").textContent=`티어 · ${p.tier}`;$("accountPointsDisplay").textContent=`${p.points} P`;$("accountRecordDisplay").textContent=`${p.matches}전 ${p.wins}승 · 누적 ${p.totalKo} KO`;
    $("accountNextDisplay").textContent=p.nextTier?`다음 티어 ${p.nextTier}까지 ${p.nextAt-p.points} P`:"최고 티어 달성!";$("accountProgressBar").style.width=p.nextTier?`${clamp((p.points-p.tierStart)/(p.nextAt-p.tierStart)*100,0,100)}%`:"100%";
  }
  function openAccount(){$("accountStatus").textContent="";renderAccount();show("accountOverlay",true);}
  async function loadProfile(){const user=window.yungeonAuth?.auth?.currentUser;if(!user){authToken="";accountProfile=null;renderAccount();return;}try{authToken=await user.getIdToken();const response=await fetch("/api/me",{headers:{Authorization:`Bearer ${authToken}`}}),data=await response.json();if(!response.ok)throw Error(data.error||"프로필을 불러오지 못했습니다.");accountProfile=data.profile;renderAccount();}catch(error){accountProfile=null;renderAccount();$("accountStatus").textContent=error.message||"게임 서버에 연결할 수 없습니다.";}}
  async function googleLogin(){try{const f=window.yungeonAuth;if(!f)throw Error("Firebase를 불러오는 중입니다. 잠시 후 다시 눌러 주세요.");$("accountStatus").textContent="Google 로그인 중...";const result=await f.signInWithPopup(f.auth,f.provider);authToken=await result.user.getIdToken();await loadProfile();$("accountStatus").textContent="Google 로그인 완료!";loadGlobalBoard();}catch(error){$("accountStatus").textContent=error?.code==="auth/popup-closed-by-user"?"로그인 창이 닫혔습니다.":error.message||"Google 로그인에 실패했습니다.";}}
  async function loadGlobalBoard(){if(location.protocol==="file:"){$("globalBoard").textContent="온라인 서버 실행 후 이용할 수 있습니다.";return;}try{const response=await fetch("/api/leaderboard"),data=await response.json();$("globalBoard").innerHTML=data.players.length?data.players.slice(0,5).map((p,i)=>`<div class="global-row"><span>${i+1}. ${escapeHtml(p.name)} <small>${escapeHtml(p.tier)}</small></span><b>${p.points} P</b></div>`).join(""):"아직 기록이 없습니다.";}catch{$("globalBoard").textContent="랭킹을 불러오지 못했습니다.";}}
  function beginSolo(){closeSocket();mode="solo";onlineStatus="playing";const bots=roster.filter(c=>c.id!==selectedCharacterId).sort(()=>Math.random()-.5).slice(0,3);players=[newPlayer(1,$("nameInput").value.trim()||combat.getCharacter(selectedCharacterId).name,360,965,selectedCharacterId),newPlayer(2,bots[0].name,360,96,bots[0].id,true),newPlayer(3,bots[1].name,150,535,bots[1].id,true),newPlayer(4,bots[2].name,570,535,bots[2].id,true)];myId=1;bullets=[];fields=[];soloWorld.fields=fields;effects=[];timeLeft=180;clock=0;nextChallenge=10;lastAutoChallenge=0;lastEarned=null;endShown=false;challenge=null;angle=-Math.PI/2;jumpTargeting=false;show("targetHint",false);for(const id of["menuOverlay","lobbyOverlay","endOverlay","missionOverlay","characterOverlay"])show(id,false);sound.setMode("battle");toast("⚔ 연습전 시작! 3분 동안 싸워 보세요");}
  function finish(){if(endShown)return;endShown=true;show("missionOverlay",false);const sorted=[...players].sort((a,b)=>b.ko-a.ko||a.deaths-b.deaths),self=me();$("endTitle").textContent=sorted[0]?.id===myId?"우승! 🎉":"경기 종료!";$("endDescription").textContent=`${self?.ko||0} KO · ${self?.deaths||0}번 쓰러짐${mode==="online"&&lastEarned!==null?` · +${lastEarned} P · ${accountProfile?.tier||""}`:""}`;$("endScores").innerHTML=sorted.map((p,i)=>`${i+1}위 · ${escapeHtml(p.name)} (${escapeHtml(combat.getCharacter(p.characterId).name)}) — ${p.ko} KO`).join("<br>");show("endOverlay",true);sound.play("end");sound.setMode("menu");}
  function updateSolo(dt){clock+=dt;timeLeft=Math.max(0,180-clock);if(timeLeft<=0){finish();return;}const now=performance.now(),self=me();
    if(self?.alive){const m=movement();move(self,m.x,m.y,dt);self.angle=angle;if(fireHeld)combat.fireBasic(soloWorld,self,now);}
    for(const p of players){if(!p.alive){if(now>=p.respawnAt){const [x,y]=spawn[Math.floor(rand(0,spawn.length))];p.x=x;p.y=y;p.hp=p.maxHp;p.ammo=3;p.shieldHits=0;p.alive=true;p.invulnUntil=now+3000;p.lastHurt=now;p.burnUntil=0;p.poisonUntil=0;p.slowUntil=0;p.rootUntil=0;visualEvent({type:"respawn",x,y,id:p.id},true);}continue;}
      if(p.bot){const targets=players.filter(v=>v.id!==p.id&&v.alive).sort((a,b)=>d2(p.x,p.y,a.x,a.y)-d2(p.x,p.y,b.x,b.y)),target=targets[0];if(target){const d=Math.hypot(target.x-p.x,target.y-p.y),a=Math.atan2(target.y-p.y,target.x-p.x);p.angle=a;if(now>p.aiChange){p.aiDir=rand(-1,1);p.aiChange=now+rand(900,2700);}const forward=d>260?1:d<155?-.8:.12;move(p,Math.cos(a)*forward+Math.cos(a+Math.PI/2)*p.aiDir*.65,Math.sin(a)*forward+Math.sin(a+Math.PI/2)*p.aiDir*.65,dt);if(d<600&&Math.random()<dt*2.7)combat.fireBasic(soloWorld,p,now);if(d<190&&now>=p.skillReadyAt&&Math.random()<dt*.35)combat.useSkill(soloWorld,p,now);if(p.super>=100&&Math.random()<dt*.25)combat.useSuper(soloWorld,p,now,p.characterId==="jumper"?{x:target.x,y:target.y}:null);}}
      if(p.ammo<3&&now-p.lastReload>=1600){p.ammo++;p.lastReload=now;}if(now-p.lastHurt>=5000&&p.hp<p.maxHp)p.hp=Math.min(p.maxHp,p.hp+5*dt);
    }
    combat.tick(soloWorld,now);
    bullets=bullets.filter(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||blocked(b.x,b.y,Math.min(b.size,6))){particle(b.x,b.y,b.color,3,.5);return false;}for(const p of players)if(p.id!==b.owner&&p.alive&&d2(p.x,p.y,b.x,b.y)<(19+b.size)**2){if(soloDamage(p,b.damage,b.owner)&&b.status)combat.applyStatus(p,b.status,now,b.owner);return false;}return true;});
    if(clock>=nextChallenge&&!challenge){openMission();nextChallenge=clock+38;}
  }
  async function beginOnline(create){const user=window.yungeonAuth?.auth?.currentUser;if(!user){$("menuStatus").textContent="온라인 대전은 먼저 Google로 로그인해 주세요.";openAccount();return;}const code=$("roomInput").value.trim().toUpperCase();if(!create&&!/^[A-Z0-9]{4}$/.test(code)){$("menuStatus").textContent="방 코드 4자리를 입력해 주세요.";return;}if(location.protocol==="file:"){$("menuStatus").textContent="온라인 대전은 npm start로 서버를 실행한 뒤 접속해 주세요.";return;}
    $("menuStatus").textContent="서버에 연결 중...";try{authToken=await user.getIdToken();await loadProfile();if(!accountProfile)throw Error("로그인 프로필을 불러오지 못했습니다.");closeSocket();const socket=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}`);ws=socket;socket.onopen=()=>socket.send(JSON.stringify({type:create?"create":"join",token:authToken,code,characterId:selectedCharacterId}));socket.onmessage=e=>{try{handleMessage(JSON.parse(e.data));}catch(error){console.error(error);}};socket.onerror=()=>{$("menuStatus").textContent="서버에 연결할 수 없습니다.";};socket.onclose=()=>{if(ws!==socket)return;ws=null;if(mode==="online"&&!endShown){mode="menu";sound.setMode("menu");show("lobbyOverlay",false);show("missionOverlay",false);show("menuOverlay",true);$("menuStatus").textContent="서버 연결이 끊어졌습니다.";}};}catch(error){$("menuStatus").textContent=error.message||"서버에 연결할 수 없습니다.";}}
  function closeSocket(){if(ws){const socket=ws;ws=null;socket.close();}}
  function send(message){if(ws?.readyState===1)ws.send(JSON.stringify(message));}
  function handleMessage(message){if(message.type==="error"){$("menuStatus").textContent=message.message;$("lobbyStatus").textContent=message.message;toast(message.message);return;}
    if(message.type==="joined"){mode="online";onlineStatus="waiting";myId=message.id;roomCode=message.code;hostId=message.host;lastEarned=null;$("roomCode").textContent=message.code;show("menuOverlay",false);show("lobbyOverlay",true);return;}
    if(message.type==="result"){lastEarned=message.earned;accountProfile=message.profile;renderAccount();loadGlobalBoard();toast(`경기 기록 저장! +${message.earned} P · ${message.profile.tier}`);return;}
    if(message.type==="state"){const previous=onlineStatus;onlineStatus=message.status;roomCode=message.code;hostId=message.host;timeLeft=message.remaining;const existing=new Map(players.map(p=>[p.id,p]));players=message.players.map(p=>{const old=existing.get(p.id);return{...p,x:old?.x??p.x,y:old?.y??p.y,tx:p.x,ty:p.y};});bullets=message.bullets;fields=message.fields||[];for(const ev of message.events||[])visualEvent(ev,false);
      if(message.status==="waiting"){show("lobbyOverlay",true);$("lobbyList").innerHTML=players.map(p=>`<span style="color:${p.color}">●</span> ${escapeHtml(p.name)} · ${escapeHtml(combat.getCharacter(p.characterId).name)} ${p.id===message.host?"👑":""}`).join("<br>");$("startBtn").disabled=myId!==message.host||players.length<2;$("lobbyStatus").textContent=players.length<2?"친구가 1명 이상 참가하면 시작할 수 있어요.":`${players.length}/4명 준비 완료`;}
      if(message.status==="playing"){if(previous!=="playing"){clock=.001;lastAutoChallenge=performance.now()/1000+14;sound.setMode("battle");}show("lobbyOverlay",false);if(endShown){endShown=false;show("endOverlay",false);}}
      if(message.status==="ended")finish();return;}
    if(message.type==="challenge"){challenge={...message,answer:null};renderMission();return;}
    if(message.type==="challengeResult"){challenge=null;show("missionOverlay",false);if(message.correct){sound.play("correct");sound.play("item");toast(`정답! ${rewardNames[message.reward]}`);}else{sound.play("wrong");toast(message.expired?"시간 초과!":"아쉬워요, 다음 문제에 도전!");}return;}
    if(message.type==="abilityResult"&&!message.ok&&message.reason==="range")toast("점프 범위 밖이거나 장애물이 있습니다.");
  }
  function useSkill(){if(endShown||onlineStatus!=="playing")return;const self=me();if(!self||!self.alive)return;if(mode==="online"){send({type:"skill"});return;}const result=combat.useSkill(soloWorld,self,performance.now());if(!result.ok&&result.reason==="cooldown")toast("스킬 재사용 대기 중입니다.");}
  function useSuper(){if(endShown||onlineStatus!=="playing")return;const self=me();if(!self||!self.alive||self.super<100)return;if(self.characterId==="jumper"){jumpTargeting=!jumpTargeting;show("targetHint",jumpTargeting);if(jumpTargeting)toast("맵 절반 이내 착지점을 클릭하거나 터치하세요");return;}
    if(mode==="online")send({type:"super",x:pointerPosition?.x,y:pointerPosition?.y});else{const result=combat.useSuper(soloWorld,self,performance.now(),pointerPosition);if(!result.ok)toast("필살기를 사용할 수 없습니다.");}
  }
  function jumpTo(point){const self=me();if(!self)return;const dist=Math.hypot(point.x-self.x,point.y-self.y);if(dist>525||dist<35||blocked(point.x,point.y,21)){toast("점프 범위 밖이거나 장애물이 있습니다.");return;}jumpTargeting=false;show("targetHint",false);if(mode==="online")send({type:"super",x:point.x,y:point.y});else combat.useSuper(soloWorld,self,performance.now(),point);}
  function openMission(){if(challenge||mode==="menu"||endShown||onlineStatus!=="playing")return;if(mode==="online"){send({type:"challenge"});return;}if(clock<nextChallenge)return;const item=words[Math.floor(rand(0,words.length))],options=[item[2]];while(options.length<4){const value=words[Math.floor(rand(0,words.length))][2];if(!options.includes(value))options.push(value);}options.sort(()=>Math.random()-.5);challenge={term:item[0],pronunciation:item[1],options,answer:options.indexOf(item[2]),until:performance.now()+14000};nextChallenge=clock+30;renderMission();}
  function renderMission(){$("missionTerm").textContent=challenge.term;$("missionPron").textContent=challenge.pronunciation;$("choices").innerHTML="";challenge.options.forEach((option,index)=>{const button=document.createElement("button");button.className="choice";button.textContent=option;button.onclick=()=>answerMission(index);$("choices").appendChild(button);});show("missionOverlay",true);playWord();}
  let activeUtterance=null;function playWord(){if(!challenge)return;if(!("speechSynthesis" in window)){toast("이 브라우저는 TTS를 지원하지 않아요");return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(challenge.pronunciation);utterance.lang="ko-KR";utterance.rate=.85;utterance.pitch=1;const voice=window.speechSynthesis.getVoices().find(v=>v.lang&&v.lang.toLowerCase().startsWith("ko"));if(voice)utterance.voice=voice;activeUtterance=utterance;window.speechSynthesis.speak(utterance);}
  function answerMission(index){if(!challenge)return;if(mode==="online"){send({type:"answer",index});return;}const correct=index===challenge.answer;challenge=null;show("missionOverlay",false);if(correct){sound.play("correct");const self=me(),reward=["shield","heal","boost","super"][Math.floor(rand(0,4))];if(reward==="shield")self.shieldHits=2;if(reward==="heal")self.hp=Math.min(self.maxHp,self.hp+45);if(reward==="boost")self.bonusDamageUntil=performance.now()+10000;if(reward==="super")self.super=Math.min(100,self.super+60);visualEvent({type:"reward",x:self.x,y:self.y,id:self.id,reward},true);toast(`정답! ${rewardNames[reward]}`);}else{sound.play("wrong");toast("아쉬워요! 다음 문제에 도전하세요");}}
  function updateHud(){const self=me(),max=self?.maxHp||combat.getCharacter(selectedCharacterId).hp,sec=Math.max(0,Math.ceil(timeLeft));$("clock").textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,"0")}`;$("hudMode").textContent=mode==="online"?"온라인 대전":"연습전";$("hudKo").textContent=`${self?.ko||0} KO`;$("pilotName").textContent=self?.name||combat.getCharacter(selectedCharacterId).name;document.querySelector(".pilot-face").textContent=combat.getCharacter(self?.characterId||selectedCharacterId).icon;$("hpText").textContent=`${Math.ceil(self?.hp||0)} / ${max}`;$("hpBar").style.width=`${clamp((self?.hp||0)/max*100,0,100)}%`;for(const id of["superText","hudSuperText"])$(id).textContent=`${Math.floor(self?.super||0)}%`;for(const id of["superBar","hudSuper"])$(id).style.width=`${self?.super||0}%`;$("koText").textContent=self?.ko||0;[...$("ammo").children].forEach((el,i)=>el.classList.toggle("ready",i<(self?.ammo||0)));$("liveLabel").textContent=mode==="menu"?"대기 중":mode==="online"?"온라인 연결됨":"연습전 진행 중";$("leaderboard").innerHTML=[...players].sort((a,b)=>b.ko-a.ko||a.deaths-b.deaths).map((p,i)=>`<div class="leader"><span class="rank">${i+1}</span><span class="dot" style="background:${p.color}"></span><span class="name">${escapeHtml(p.name)} ${combat.getCharacter(p.characterId).icon}${p.id===myId?" (나)":""}</span><span class="kos">${p.ko} KO</span></div>`).join("");const remaining=mode==="solo"?Math.max(0,Math.ceil(nextChallenge-clock)):0;$("missionCooldown").textContent=challenge?"미션 진행 중":mode==="solo"&&remaining>0?`${remaining}초 후 다시 도전 가능`:"정답 보상 4종 중 랜덤 지급";$("missionBtn").disabled=mode==="menu"||onlineStatus!=="playing"||!!challenge||(mode==="solo"&&remaining>0);$("mobileSuper").disabled=!self||self.super<100;const cd=Math.max(0,Math.ceil(((self?.skillReadyAt||0)-nowGame())/1000)),skill=combat.getCharacter(self?.characterId||selectedCharacterId).skill;$("skillLabel").textContent=cd?`${skill.name} ${cd}초`:skill.name;$("skillButton").classList.toggle("ready",!!self&&!cd);$("mobileSkill").disabled=!self||cd>0;}
  function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);}function roundRect(x,y,w,h,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();}
    function drawMap(){rect(0,0,W,H,"#ed986c");for(let y=0;y<H;y+=30)for(let x=0;x<W;x+=30){rect(x,y,30,30,(Math.floor(x/30)+Math.floor(y/30))%2?"#ed986c":"#f6a377");if((x*17+y*23)%11===0)rect(x+4,y+5,3,3,"#ffc09555");}for(let i=0;i<45;i++){const x=(i*157+23)%W,y=(i*251+71)%H;circle(x,y,2,"#fff1bf44");}
    for(const [x,y,w,h] of waters){roundRect(x+5,y+7,w,h,9,"#995d4a");roundRect(x,y,w,h,8,"#8ee0f5");const g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,"#35b3e5");g.addColorStop(1,"#198cc8");roundRect(x+4,y+4,w-8,h-8,5,g);ctx.strokeStyle="#ffffff38";ctx.lineWidth=2;for(let yy=y+26;yy<y+h;yy+=42){ctx.beginPath();ctx.moveTo(x+12,yy);ctx.quadraticCurveTo(x+w*.45,yy-6,x+w-14,yy);ctx.stroke();}}
    for(const [x,y,w,h] of bushes)drawBush(x,y,w,h);
    // central stone arena
    circle(360,542,122,"#b76659");circle(360,533,120,"#77dbef");const g=ctx.createRadialGradient(330,490,10,360,533,116);g.addColorStop(0,"#a9c5df");g.addColorStop(.65,"#799aba");g.addColorStop(1,"#567fa3");circle(360,533,115,g);circle(360,533,94,"#b4c7d269");circle(360,533,64,"#537c9a66");circle(360,533,32,"#527e9a55");ctx.strokeStyle="#d3edf574";ctx.lineWidth=5;ctx.beginPath();ctx.arc(360,533,108,3.4,5.8);ctx.stroke();
    for(const [x,y,w,h] of walls)drawWall(x,y,w,h);
    for(const [x,y,c] of [[297,28,"#fb6875"],[360,28,"#fb6875"],[423,28,"#fb6875"],[297,1053,"#36b5e9"],[360,1053,"#36b5e9"],[423,1053,"#36b5e9"]]){circle(x,y+4,26,"#874f59");circle(x,y,24,c);circle(x-5,y-6,17,"#ffffff25");}
    for(const [x,y] of [[222,425],[498,425],[222,653],[498,653]]){circle(x,y+8,15,"#a76247");circle(x,y,14,"#c94d75");circle(x,y+2,8,"#ffad6b");circle(x,y-5,5,"#542a48");}
  }
  function drawBush(x,y,w,h){roundRect(x+2,y+8,w,h,4,"#8c4a69");rect(x,y,w,h,"#b668ab");for(let yy=y;yy<y+h;yy+=19)for(let xx=x;xx<x+w;xx+=17){ctx.fillStyle=((xx+yy)%3)?"#cf81bd":"#a6549d";ctx.beginPath();ctx.moveTo(xx,yy+19);ctx.lineTo(xx+8.5,yy);ctx.lineTo(xx+17,yy+19);ctx.fill();}rect(x,y+h-4,w,4,"#754466");}
  function drawWall(x,y,w,h){roundRect(x+3,y+9,w,h,3,"#955a36");const tile=30;for(let xx=x;xx<x+w;xx+=tile)for(let yy=y;yy<y+h;yy+=tile){const tw=Math.min(tile,w-(xx-x)),th=Math.min(tile,h-(yy-y));rect(xx,yy,tw,th,"#104e56");rect(xx+2,yy+2,tw-4,th-5,"#1ec4a5");rect(xx+5,yy+5,tw-10,Math.max(4,th-12),"#158e83");rect(xx+8,yy+6,Math.max(3,tw-16),3,"#63e4c4");rect(xx+3,yy+th-10,tw-6,7,"#ad622c");rect(xx+9,yy+th-8,Math.max(2,tw-18),4,"#d28a3c");}}

  function drawPlayer(p){if(!p.alive)return;const c=combat.getCharacter(p.characterId),now=nowGame();let x=p.x,y=p.y;if(p.jump){const t=clamp((now-p.jump.startAt)/(p.jump.landAt-p.jump.startAt),0,1);x=p.jump.fromX+(p.jump.toX-p.jump.fromX)*t;y=p.jump.fromY+(p.jump.toY-p.jump.fromY)*t;circle(p.jump.toX,p.jump.toY,120,"#ffe58826");ctx.strokeStyle="#ffe588ae";ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.jump.toX,p.jump.toY,120,0,TAU);ctx.stroke();y-=Math.sin(t*Math.PI)*95;}
    ctx.save();ctx.translate(x,y);const bush=bushes.some(([bx,by,bw,bh])=>x>bx&&x<bx+bw&&y>by&&y<by+bh);if(bush&&p.id!==myId)ctx.globalAlpha=.58;if(p.stealthUntil>now&&p.id!==myId)ctx.globalAlpha=.3;circle(3,14,22,"#1b284a77");if(p.shieldHits>0){ctx.strokeStyle="#a8f5ff";ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,28,0,TAU*p.shieldHits/2);ctx.stroke();}if(p.invulnUntil>now){ctx.strokeStyle="#fff4a7";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,33,0,TAU);ctx.stroke();}if(p.bonusDamageUntil>now){ctx.strokeStyle="#ffd571";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,36,0,TAU);ctx.stroke();}
    ctx.rotate(p.angle+Math.PI/2);roundRect(-7,-33,14,22,4,"#26374d");roundRect(-5,-35,10,18,3,"#fff4ae");const body=ctx.createLinearGradient(-20,-20,19,20);body.addColorStop(0,"#fff");body.addColorStop(.24,c.color);body.addColorStop(1,"#344b72");circle(0,0,c.id==="gear"?25:22,"#223451");circle(0,-3,c.id==="gear"?22:19,body);ctx.rotate(-p.angle-Math.PI/2);ctx.font=c.id==="gear"?"23px sans-serif":"20px sans-serif";ctx.textAlign="center";ctx.fillText(c.icon,0,5);ctx.restore();ctx.save();ctx.font="900 12px Nunito, sans-serif";ctx.textAlign="center";ctx.lineWidth=3;ctx.strokeStyle="#172037";ctx.strokeText(p.name,x,y-47);ctx.fillStyle="#fff";ctx.fillText(p.name,x,y-47);roundRect(x-25,y-40,50,7,3,"#26394a");roundRect(x-25,y-40,50*clamp(p.hp/(p.maxHp||c.hp),0,1),7,3,p.id===myId?"#7ef9be":"#ff6e85");ctx.restore();}
  function drawBullet(b){ctx.save();ctx.shadowColor=b.color;ctx.shadowBlur=b.superShot?22:13;circle(b.x,b.y,b.size||7,b.color);circle(b.x-2,b.y-2,(b.size||7)*.43,"#fff8d8");ctx.restore();}
  function drawEffects(dt){for(const e of effects){e.life-=dt;e.x+=e.vx*dt;e.y+=e.vy*dt;e.vy+=e.text?0:230*dt;if(e.life<=0)continue;ctx.save();ctx.globalAlpha=clamp(e.life/e.max,0,1);if(e.text){ctx.font="900 19px Nunito, sans-serif";ctx.textAlign="center";ctx.lineWidth=4;ctx.strokeStyle="#17263d";ctx.strokeText(e.text,e.x,e.y);ctx.fillStyle=e.color;ctx.fillText(e.text,e.x,e.y);}else circle(e.x,e.y,e.size,e.color);ctx.restore();}effects=effects.filter(e=>e.life>0);}
  function draw(dt){ctx.clearRect(0,0,W,H);drawMap();for(const field of fields){ctx.fillStyle=`${field.color||"#a4e9c2"}35`;ctx.beginPath();ctx.arc(field.x,field.y,field.radius,0,TAU);ctx.fill();ctx.strokeStyle=field.color||"#a4e9c2";ctx.lineWidth=3;ctx.stroke();}for(const b of bullets)drawBullet(b);for(const p of players)drawPlayer(p);drawEffects(dt);
    if(jumpTargeting&&me()){const self=me();ctx.strokeStyle="#ffdd6f9c";ctx.lineWidth=4;ctx.setLineDash([12,9]);ctx.beginPath();ctx.arc(self.x,self.y,525,0,TAU);ctx.stroke();if(pointerPosition){const okay=Math.hypot(pointerPosition.x-self.x,pointerPosition.y-self.y)<=525&&!blocked(pointerPosition.x,pointerPosition.y,21);ctx.strokeStyle=okay?"#a5f5b8":"#ff7c80";ctx.beginPath();ctx.arc(pointerPosition.x,pointerPosition.y,120,0,TAU);ctx.stroke();}ctx.setLineDash([]);}
    if(mode==="menu"){ctx.fillStyle="#24355954";ctx.fillRect(0,0,W,H);}if(mode!=="menu"&&me()&&!me().alive){ctx.fillStyle="#0f1b3a9c";ctx.fillRect(0,0,W,H);ctx.textAlign="center";ctx.font="900 40px Nunito, sans-serif";ctx.fillStyle="#fff";ctx.fillText("잠시 후 부활!",W/2,H/2);ctx.font="900 24px Nunito, sans-serif";ctx.fillText(`${Math.max(0,Math.ceil((me().respawnAt-nowGame())/1000))}초`,W/2,H/2+38);}}
  function loop(now){const dt=Math.min((now-last)/1000,.05);last=now;frame++;if(mode==="solo"&&!endShown)updateSolo(dt);if(mode==="online"&&onlineStatus==="playing"&&!endShown){clock+=dt;for(const p of players){p.x+=(p.tx-p.x)*Math.min(1,dt*13);p.y+=(p.ty-p.y)*Math.min(1,dt*13);}if(frame%2===0){const m=movement();send({type:"input",x:m.x,y:m.y,angle,fire:fireHeld});}if(now/1000>=lastAutoChallenge&&!challenge){send({type:"challenge"});lastAutoChallenge=now/1000+38;}}
    if(challenge){const remain=Math.max(0,Math.ceil((challenge.until-nowGame())/1000));$("missionTime").textContent=`남은 시간 ${remain}초`;if(remain<=0&&mode==="solo"){challenge=null;show("missionOverlay",false);sound.play("wrong");toast("시간 초과! 다음 미션에 도전하세요");}}
    draw(dt);if(frame%5===0)updateHud();requestAnimationFrame(loop);}
  function movement(){return{x:clamp((keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0)+moveTouch.x,-1,1),y:clamp((keys.has("s")||keys.has("arrowdown")?1:0)-(keys.has("w")||keys.has("arrowup")?1:0)+moveTouch.y,-1,1)};}
  function pointFromEvent(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
  canvas.addEventListener("pointermove",e=>{pointerPosition=pointFromEvent(e);if(e.pointerType==="mouse"&&!jumpTargeting&&me())angle=Math.atan2(pointerPosition.y-me().y,pointerPosition.x-me().x);});
  canvas.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse"&&e.button!==0)return;pointerPosition=pointFromEvent(e);if(jumpTargeting){jumpTo(pointerPosition);return;}if(e.pointerType==="mouse"){if(me())angle=Math.atan2(pointerPosition.y-me().y,pointerPosition.x-me().x);fireHeld=true;}});
  window.addEventListener("pointerup",e=>{if(e.pointerType==="mouse")fireHeld=false;});canvas.addEventListener("contextmenu",e=>e.preventDefault());
  window.addEventListener("keydown",e=>{const key=e.key.toLowerCase();if([" ","arrowup","arrowdown","arrowleft","arrowright"].includes(key))e.preventDefault();if(e.target instanceof HTMLInputElement)return;keys.add(key);if(key===" "&&!e.repeat)useSuper();if(key==="e"&&!e.repeat)useSkill();if(key==="q"&&!e.repeat)openMission();if(key==="escape"&&jumpTargeting){jumpTargeting=false;show("targetHint",false);}});window.addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));window.addEventListener("blur",()=>{keys.clear();fireHeld=false;moveTouch={x:0,y:0};});
  function setupStick(id,onChange){const el=$(id),knob=el.querySelector(".knob");let pointer=null;const end=e=>{if(pointer!==e.pointerId)return;pointer=null;knob.style.left="50%";knob.style.top="50%";onChange(0,0,false);};el.addEventListener("pointerdown",e=>{pointer=e.pointerId;el.setPointerCapture(pointer);update(e);});el.addEventListener("pointermove",e=>{if(pointer===e.pointerId)update(e);});el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end);function update(e){const r=el.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),max=r.width*.35,len=Math.hypot(dx,dy)||1,scale=Math.min(1,max/len),x=dx*scale,y=dy*scale;knob.style.left=`calc(50% + ${x}px)`;knob.style.top=`calc(50% + ${y}px)`;onChange(clamp(x/max,-1,1),clamp(y/max,-1,1),true);}}
  setupStick("moveStick",(x,y)=>{moveTouch={x,y};});setupStick("aimStick",(x,y,active)=>{fireHeld=active;if(active&&Math.hypot(x,y)>.18)angle=Math.atan2(y,x);});
  $("soloBtn").onclick=beginSolo;$("createBtn").onclick=()=>beginOnline(true);$("joinBtn").onclick=()=>beginOnline(false);$("roomInput").addEventListener("input",e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,""));$("startBtn").onclick=()=>send({type:"start"});$("copyBtn").onclick=()=>navigator.clipboard?.writeText(roomCode).then(()=>toast("방 코드를 복사했어요"));$("leaveBtn").onclick=()=>{closeSocket();mode="menu";players=[];sound.setMode("menu");show("lobbyOverlay",false);show("menuOverlay",true);};
  $("missionBtn").onclick=openMission;$("mobileMission").onclick=openMission;$("listenBtn").onclick=playWord;$("skillButton").onclick=useSkill;$("mobileSkill").onclick=useSkill;$("mobileSuper").onclick=useSuper;$("againBtn").onclick=()=>{closeSocket();mode="menu";onlineStatus="";players=[];clock=0;fields=[];sound.setMode("menu");show("endOverlay",false);show("menuOverlay",true);};
  $("characterOpenBtn").onclick=()=>{renderCharacterSelect();show("characterOverlay",true);};$("characterCloseBtn").onclick=()=>show("characterOverlay",false);
  $("accountOpenBtn").onclick=openAccount;$("sideAccountBtn").onclick=openAccount;$("accountCloseBtn").onclick=()=>show("accountOverlay",false);$("googleLoginBtn").onclick=googleLogin;
  $("logoutBtn").onclick=async()=>{if(window.yungeonAuth)await window.yungeonAuth.signOut(window.yungeonAuth.auth);authToken="";accountProfile=null;renderAccount();$("accountStatus").textContent="로그아웃했습니다.";if(mode==="online"){closeSocket();mode="menu";onlineStatus="";players=[];sound.setMode("menu");show("lobbyOverlay",false);show("endOverlay",false);show("menuOverlay",true);}};
  function renderAudio(){const muted=sound.muted;$("muteButton").textContent=muted?"🔇 음소거":"🔊 소리 켜짐";$("muteButton").setAttribute("aria-pressed",String(muted));$("bgmVolume").value=Math.round(sound.bgmVolume*100);$("sfxVolume").value=Math.round(sound.sfxVolume*100);$("bgmValue").textContent=$("bgmVolume").value;$("sfxValue").textContent=$("sfxVolume").value;}
  $("muteButton").onclick=()=>{sound.unlock();sound.setMuted(!sound.muted);renderAudio();};$("audioToggle").onclick=()=>$("audioPanel").classList.toggle("collapsed");$("bgmVolume").oninput=e=>{sound.unlock();sound.setBgmVolume(e.target.value/100);renderAudio();};$("sfxVolume").oninput=e=>{sound.unlock();sound.setSfxVolume(e.target.value/100);renderAudio();};
  window.addEventListener("pointerdown",()=>sound.unlock(),{once:true});window.addEventListener("keydown",()=>sound.unlock(),{once:true});
  renderCharacterSelect();renderAccount();renderAudio();sound.setMode("menu");const waitAuth=setInterval(()=>{if(window.yungeonAuth){clearInterval(waitAuth);window.yungeonAuth.onAuthStateChanged(window.yungeonAuth.auth,async user=>{if(user)await loadProfile();else{authToken="";accountProfile=null;renderAccount();}});}},50);loadGlobalBoard();updateHud();requestAnimationFrame(loop);
})();
